stages:
  - package
  - test

variables:
  DOCKER_IMAGE:

build-and-push-docker:
  stage: package
  script:
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_USER_PASSWORD $NCR_REGISTRY
    - docker build -t $DOCKER_IMAGE $CI_PROJECT_DIR
    - docker push $DOCKER_IMAGE
  only:
    refs:
      - branches
    changes:
      - Dockerfile
      - requirements.txt
